### PR TITLE
pg-promise fixes

### PR DESCRIPTION
**Pull request by vitaly-t**
your use of pg-promise is terribly bad - see the corrections i've made ;)

never use `Promise.all` in combination with pg-promise, see: https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes#tasks-versus-rootdirect-queries

also check out: [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) ;)

### CODE REVIEW

**Comment by Resonance1584** [comment]
Hi @vitaly-t - thank you for your input it's highly appreciated. I'm currently rewriting to add migrations and auth support and will integrate your suggested changes there.

Can you please elaborate on the behaviour of Promise.all with pg-promise queries. In the example you linked it states `return Promise.all(queries); // doesn't settle queries;` - what do you mean by doesn't settle queries - are the queries not run although the promise is resolved? Or are the queries both run but using separate connections and while functioning correctly are inefficient? Thanks.

**Comment by vitaly-t** [comment]
As per `Promise.all` protocol, it does not guarantee to settle promises, it will stop settling promises just as the first one fails, and reject immediately. Method `.batch` settles all promises no matter what.

**Comment by Resonance1584** [comment]
In the following scenario:
```js
db.tx(t => {
    return Promise.all([
        t.none('INSERT some...'),
        t.none('INSERT some...')
    ])
})
.then(() => {
    // Promise resolved - transaction committed
})
.catch(e => {
    // Promise rejected - transaction rolled back?
})
```
Would Promise.all work as expected or is there an issue with open connections?

**Comment by vitaly-t** [comment]
If the first insert fails, then NO, it won't work as expected, that's why you can only use `batch`.

**Comment by Resonance1584** [comment]
Fixed in https://github.com/endfoos/foosilator/pull/8

**Pull request closed without merging**
